<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Universal SEO & Social Metadata Engine for Coming Soon & Maintenance Mode.
 */
class CSMM_SEO {

	/**
	 * Render complete SEO, Social Meta, and Schema markup for template <head>.
	 *
	 * @param array $content
	 * @param array $settings
	 * @param array $seo_settings
	 */
	public static function render_meta_tags( $content = array(), $settings = array(), $seo_settings = array() ) {
		$site_name = get_bloginfo( 'name' );
		$site_url  = home_url( '/' );

		$mode = isset( $settings['website_mode'] ) ? intval( $settings['website_mode'] ) : 3;

		// Title & Description
		$title = ! empty( $seo_settings['meta_title'] )
			? $seo_settings['meta_title']
			: ( ! empty( $content['title'] ) ? $content['title'] : $site_name );

		$description = ! empty( $seo_settings['meta_description'] )
			? $seo_settings['meta_description']
			: ( ! empty( $content['description'] ) ? $content['description'] : get_bloginfo( 'description' ) );

		// Clean description of any HTML tags
		$description = wp_strip_all_tags( $description );

		// Robots Directive
		// In Mode 2 (Maintenance Mode) default to noindex, nofollow to protect existing SEO
		// In Mode 1 (Coming Soon Mode) default to index, follow to rank pre-launch
		$robots_override = isset( $seo_settings['robots_meta'] ) ? $seo_settings['robots_meta'] : 'auto';
		if ( 'noindex' === $robots_override ) {
			$robots = 'noindex, nofollow';
		} elseif ( 'index' === $robots_override ) {
			$robots = 'index, follow';
		} else {
			$robots = ( 2 === $mode ) ? 'noindex, nofollow' : 'index, follow';
		}

		// Open Graph Image
		$og_image = '';
		if ( ! empty( $seo_settings['og_image_id'] ) && is_numeric( $seo_settings['og_image_id'] ) ) {
			$img_src = wp_get_attachment_image_src( $seo_settings['og_image_id'], 'large' );
			if ( $img_src ) {
				$og_image = $img_src[0];
			}
		} elseif ( ! empty( $content['logo'] ) && is_numeric( $content['logo'] ) ) {
			$logo_src = wp_get_attachment_image_src( $content['logo'], 'large' );
			if ( $logo_src ) {
				$og_image = $logo_src[0];
			}
		}

		// Google Analytics / Tracking ID if provided
		$ga_id = ! empty( $seo_settings['google_analytics_id'] ) ? sanitize_text_field( $seo_settings['google_analytics_id'] ) : '';

		?>
		<!-- Primary Meta Tags Generated by Coming Soon Maintenance Mode Pro -->
		<meta name="robots" content="<?php echo esc_attr( $robots ); ?>" />
		<link rel="canonical" href="<?php echo esc_url( $site_url ); ?>" />

		<!-- Open Graph / Facebook / LinkedIn -->
		<meta property="og:type" content="website" />
		<meta property="og:url" content="<?php echo esc_url( $site_url ); ?>" />
		<meta property="og:title" content="<?php echo esc_attr( $title ); ?>" />
		<meta property="og:description" content="<?php echo esc_attr( $description ); ?>" />
		<meta property="og:site_name" content="<?php echo esc_attr( $site_name ); ?>" />
		<?php if ( ! empty( $og_image ) ) : ?>
		<meta property="og:image" content="<?php echo esc_url( $og_image ); ?>" />
		<?php endif; ?>

		<!-- Twitter / X -->
		<meta name="twitter:card" content="summary_large_image" />
		<meta name="twitter:url" content="<?php echo esc_url( $site_url ); ?>" />
		<meta name="twitter:title" content="<?php echo esc_attr( $title ); ?>" />
		<meta name="twitter:description" content="<?php echo esc_attr( $description ); ?>" />
		<?php if ( ! empty( $og_image ) ) : ?>
		<meta name="twitter:image" content="<?php echo esc_url( $og_image ); ?>" />
		<?php endif; ?>

		<!-- Schema.org JSON-LD Structured Data -->
		<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "WebSite",
			"name": <?php echo wp_json_encode( $site_name ); ?>,
			"url": <?php echo wp_json_encode( $site_url ); ?>,
			"description": <?php echo wp_json_encode( $description ); ?>
		}
		</script>

		<?php if ( ! empty( $ga_id ) ) : ?>
		<!-- Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo esc_attr( $ga_id ); ?>"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
			gtag('config', '<?php echo esc_js( $ga_id ); ?>');
		</script>
		<?php endif; ?>
		<?php
	}
}
